import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import "./globals.css";
import { ConvexProvider, ConvexReactClient } from "convex/react";
import { ConvexClientProvider } from "./ConvexClientProvider";


export const metadata: Metadata = {
  title: "website",
  description: "Generated by create next app",
};

// ✅ use lowercase name here
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={poppins.className}>
          <ConvexClientProvider>{children}</ConvexClientProvider>


        </body>
      </html>
    </ClerkProvider>

  );
}
